backend:
  name: git-gateway
  branch: master
  auth_scope: repo
  auth_url: https://dev-nd1cktzyoebormj8.auth0.com/oauth/token
  base_url: https://dev-nd1cktzyoebormj8.auth0.com
  auth_provider: auth0

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "settings"
    label: "إعدادات الموقع"
    files:
      - label: "الإعلانات"
        name: "advertisements"
        file: "content/settings/advertisements-new.md"
        fields:
          - {label: "نص الإعلان", name: "adText", widget: "string", default: "مرحباً بكم في TechTouch - موقعكم المفضل للتقنية!"}
          - {label: "تفعيل الإعلان", name: "adEnabled", widget: "boolean", default: true}
      - label: "الصورة الشخصية"
        name: "profile"
        file: "content/settings/profile.md"
        fields:
          - {label: "الصورة الشخصية", name: "profileImage", widget: "image", default: "/images/default-profile.png"}
          - {label: "اسم القناة", name: "channelName", widget: "string", default: "TechTouch"}

  - name: "posts"
    label: "المنشورات"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "العنوان", name: "title", widget: "string"}
      - {label: "التاريخ", name: "date", widget: "datetime"}
      - {label: "الفئة", name: "category", widget: "select", options: ["posts", "games", "sports", "movies"]}
      - {label: "الصورة", name: "image", widget: "image", required: false}
      - {label: "المحتوى", name: "body", widget: "markdown"}
      - {label: "رابط التليجرام", name: "telegramLink", widget: "string", required: false}
      - {label: "رابط خارجي", name: "link", widget: "string", required: false}

  - name: "telegram"
    label: "قنوات التليجرام"
    folder: "content/telegram"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "اسم القناة", name: "title", widget: "string"}
      - {label: "الوصف", name: "description", widget: "string"}
      - {label: "الأيقونة", name: "icon", widget: "string", hint: "مثال: fas fa-gamepad"}

      - {label: "الترتيب", name: "order", widget: "number", default: 1}


admin_path: /cms/

