baseURL = "https://kinan.netlify.app/"
languageCode = "ar"
title = "قناة TechTouch"
defaultContentLanguage = "ar"

[params]
  description = "اضغط على أي قسم للانتقال إليه مباشرة"
  author = "TechTouch"
  
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    name = "الرئيسية"
    url = "/"
    weight = 1






[taxonomies]
  category = "category"




[[Params.collections]]
  name = "general-posts"
  label = "المنشورات (عام)"
  folder = "content/general-posts"
  create = true
  slug = "{{slug}}"
  fields =
    [
      {label = "Title", name = "title", widget = "string"},
      {label = "Publish Date", name = "date", widget = "datetime"},
      {label = "Body", name = "body", widget = "markdown"},
    ]




[[Params.collections]]
  name = "games"
  label = "الألعاب"
  folder = "content/games"
  create = true
  slug = "{{slug}}"
  fields =
    [
      {label = "Title", name = "title", widget = "string"},
      {label = "Publish Date", name = "date", widget = "datetime"},
      {label = "Body", name = "body", widget = "markdown"},
    ]


