backend:
  name: git-gateway
  branch: master

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "المنشورات (عام)"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "العنوان", name: "title", widget: "string", required: true}
      - {label: "التاريخ", name: "date", widget: "datetime", required: true}
      - {label: "المسودة", name: "draft", widget: "boolean", default: false, required: true}
      - {label: "الوصف", name: "description", widget: "text", required: true}
      - {label: "الصورة (اختيارية)", name: "image", widget: "image", required: false}
      - {label: "الملف (اختياري)", name: "file", widget: "file", required: false}
      - {label: "المحتوى", name: "body", widget: "markdown", required: false}
  - name: "sports"
    label: "الرياضة"
    folder: "content/category/sports"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "العنوان", name: "title", widget: "string", required: true}
      - {label: "التاريخ", name: "date", widget: "datetime", required: true}
      - {label: "المسودة", name: "draft", widget: "boolean", default: false, required: true}
      - {label: "الوصف", name: "description", widget: "text", required: true}
      - {label: "الصورة (اختيارية)", name: "image", widget: "image", required: false}
      - {label: "الملف (اختياري)", name: "file", widget: "file", required: false}
      - {label: "المحتوى", name: "body", widget: "markdown", required: false}
  - name: "movies"
    label: "الأفلام"
    folder: "content/category/movies"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "العنوان", name: "title", widget: "string", required: true}
      - {label: "التاريخ", name: "date", widget: "datetime", required: true}
      - {label: "المسودة", name: "draft", widget: "boolean", default: false, required: true}
      - {label: "الوصف", name: "description", widget: "text", required: true}
      - {label: "الصورة (اختيارية)", name: "image", widget: "image", required: false}
      - {label: "الملف (اختياري)", name: "file", widget: "file", required: false}
      - {label: "المحتوى", name: "body", widget: "markdown", required: false}
  - name: "telegram"
    label: "قنوات التليجرام"
    folder: "content/category/telegram"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "العنوان", name: "title", widget: "string", required: true}
      - {label: "التاريخ", name: "date", widget: "datetime", required: true}
      - {label: "المسودة", name: "draft", widget: "boolean", default: false, required: true}
      - {label: "الوصف", name: "description", widget: "text", required: true}
      - {label: "الصورة (اختيارية)", name: "image", widget: "image", required: false}
      - {label: "الملف (اختياري)", name: "file", widget: "file", required: false}
      - {label: "المحتوى", name: "body", widget: "markdown", required: false}


